Replace Select2 with SlimSelect
platanus/activeadmin_addons pull request #448
Opened 2023-03-06 18:49 UTC by gmq

## Context

Select2 is difficult to configure and use with newer bundlers based on `esbuild`. Rather than attempting to make it work, this pull request replaces the library with a more up-to-date alternative while attempting to maintain similar usage.

​## Breaking Changes

This implementation replaces ActiveAdmin's jQuery events with a MutationObserver. Instead of listening to `has_many_*` events, the MutationObserver watches for new elements and initializes `slim-select` where necessary. It covers most typical use cases, but there may be scenarios that I have not taken into account.

## Changes

I added our standard ESLint configuration to accommodate the use of ES6 syntax in newer files. This may result in a lot of red lines in older files, but since they are not touched often, it shouldn't be a major issue.

## Possible Issues
It may be necessary to fork `slim-select` to fix outstanding issues since the author of the library works sporadically on it. This is alleviated in part by the fact that we don't really need any _new_ features. Once we get it working with no issues, there won't be a need for continued development, and we can contribute the fixes to upstream.

2023-03-06 18:55 UTC, monkeyci commented on lib/activeadmin_addons.rb
> +    return "slim-select" unless @default_select
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Add empty line after guard clause.

2023-03-06 18:55 UTC, monkeyci commented on spec/features/inputs/nested_select_input_spec.rb
> +        msg = "Input is too short"
⚠️ **[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Useless assignment to variable - msg.

2023-03-06 18:55 UTC, monkeyci commented on spec/features/inputs/slimselect_spec.rb
> +  context "when default config is Active Admin's default and select control has slim-select class" do
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line is too long. [101/100]

2023-03-06 18:55 UTC, monkeyci commented on spec/features/inputs/tags_input_spec.rb
> +        expect { add_slimselect_option("Not preloaded item") }.to raise_error(Capybara::ElementNotFound)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line is too long. [104/100]

2023-03-06 18:55 UTC, monkeyci commented on spec/support/capybara_helpers.rb
> +  def expect_slimselect_options_count_to_eq(count, id=nil)
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Surrounding space missing in default value assignment.

2023-03-06 18:55 UTC, monkeyci commented on spec/support/capybara_helpers.rb
> +    id = slimselect_original_select_id unless id
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Use the double pipe equals operator ||= instead.

2023-03-06 18:55 UTC, monkeyci commented on spec/support/capybara_helpers.rb
> +    display_name = item_text unless display_name
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Use the double pipe equals operator ||= instead.

2023-03-06 18:55 UTC, monkeyci commented on spec/support/capybara_helpers.rb
> +    expect(page.document).not_to have_css(".ss-content[data-id=#{id || slimselect_original_select_id}]")
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line is too long. [104/100]

2023-03-07 20:04 UTC, difernandez requested changes
Nice! Like how the js of different slim select input types is organized 💯. I leave some comments, let me know what you think. I only reviewed the code, when I have some time I'll do some testing in local and I'll come back if I find something

2023-03-07 20:57 UTC, ldlsegovia reviewed
I have manually tested the functionality in the Dummy app and I found these details:

1. Indentation:
    before:
         <img width="890" alt="image" src="https://user-images.githubusercontent.com/3026413/223549947-2b7340ef-7326-4d8b-8725-1a6d87f5e0be.png">

    after:
        <img width="524" alt="image" src="https://user-images.githubusercontent.com/3026413/223548302-cc5d4293-c550-4f61-8f62-c6c993f61b3c.png">

2. Cleaning button
    before:
        <img width="398" alt="image" src="https://user-images.githubusercontent.com/3026413/223548525-02a346e9-9fe8-419f-aa31-a698462ee3a9.png">
     after:
          <img width="440" alt="image" src="https://user-images.githubusercontent.com/3026413/223549691-91a56717-ffe4-4c77-a15b-844b1a5aaba3.png">


3. Red border:
    before:
        <img width="988" alt="image" src="https://user-images.githubusercontent.com/3026413/223548673-1c69db6f-ac9e-4119-a5be-494608835fac.png">
    after:
        <img width="1371" alt="image" src="https://user-images.githubusercontent.com/3026413/223550557-7b22eed6-d0d8-48e6-9230-2b1904505c3c.png">


4. Clean value after selecting
    before:
        <img width="726" alt="image" src="https://user-images.githubusercontent.com/3026413/223549083-a872f5ca-9e63-4821-9f74-1cd6aefc1095.png">
    after:
        <img width="487" alt="image" src="https://user-images.githubusercontent.com/3026413/223549166-ac801b0e-4373-4b1d-a3d2-f7bbfc2b9964.png">

2023-03-10 15:55 UTC, gmq commented on app/inputs/nested_level_input.rb
> +    load_data_attr(:association, value: association_name)
I use it for finding the correct nested select

https://github.com/platanus/activeadmin_addons/blob/4ab9e2c0b6321271dd7b3cb1705889ba65705188/app/javascript/activeadmin_addons/inputs/slim-select-nested.js#L51

2023-03-10 15:56 UTC, gmq commented on app/javascript/activeadmin_addons/inputs/slim-select-tags.js
> +          hiddenInput.textContent = data.text;
It appends the text next to the input, but I can't remember why I added it so I removed it.

2023-03-13 14:11 UTC, difernandez requested changes
One small detail, otherwise it's looking pretty good to me 👌I'll try the branch later today to see if there's anything else. One other thing I just remembered: we should update the docs, there are various mentions of select2 in there, as well as filenames like `select2_search.md`

2023-03-16 14:59 UTC, difernandez requested changes
Found a couple things while testing this:
- Display text is being interpreted as html. The part betewen `<>` dissapears and is an html tag in devtools

https://user-images.githubusercontent.com/12057523/225655154-c5a8f535-4f28-4748-9c76-57e182206704.mov


![image](https://user-images.githubusercontent.com/12057523/225655854-fd7ab082-839f-4912-9e77-9b8b14035231.png)

- Interactive tag is not working for me 🤔 select appears and disappears immediately

https://user-images.githubusercontent.com/12057523/225657794-87e95e37-b836-42c8-ba05-6a9d2d59caed.mov

2023-03-17 12:23 UTC, difernandez approved these changes
excellent! 👏 🚀

2023-03-17 18:05 UTC, ldlsegovia approved these changes
👏🏻

2023-03-17 18:59 UTC, merged