Remove sprockets support
platanus/activeadmin_addons pull request #451
Opened 2023-03-14 15:50 UTC by gmq

Over the years, Rails has been transitioning away from sprockets for frontend purposes. Maintaining support for both methods of installation has added complexity to every update we make.

This PR removes sprockets support, leaving only support for the Webpacker installation of ActiveAdmin. Although Webpacker is deprecated, it's easy to move files to make Addons work with other frontend bundlers.

It also removes some custom fixes for the Active Material theme.

2023-03-14 15:53 UTC, monkeyci commented on lib/generators/activeadmin_addons/install/install_generator.rb
> +          puts "ActiveAdmin Addons requires ActiveAdmin installed with webpacker. "\
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Do not write to stdout. Use Rails's logger if you want to log.

2023-03-14 15:53 UTC, monkeyci commented on lib/generators/activeadmin_addons/install/install_generator.rb
> +          "Please run 'rails generate active_admin:install --webpacker' and then 'rails generate activeadmin_addons:install'"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Line is too long. [125/100]

2023-03-16 16:42 UTC, ldlsegovia reviewed
👏🏻

2023-03-16 16:42 UTC, ldlsegovia commented on Rakefile
>    system "rake tests"
I think this task is not necessary now. Better: `rspec ./spec/lib`

2023-03-16 16:42 UTC, ldlsegovia commented on spec/dummy/config/initializers/active_admin.rb
> +  config.use_webpacker = "true"
`true` instead `"true"`

2023-03-16 16:42 UTC, ldlsegovia commented on spec/support/active_admin_helpers.rb
> +      ActiveAdmin.application.use_webpacker = "true"
same `true` instead `"true"`

2023-03-16 17:18 UTC, difernandez requested changes

2023-03-17 19:04 UTC, ldlsegovia approved these changes

2023-03-17 20:29 UTC, difernandez approved these changes
Perfect 💯

2023-03-17 20:29 UTC, merged