Remove enumerize
platanus/activeadmin_addons pull request #452
Opened 2023-03-17 20:07 UTC by gmq

In Platanus we have transitioned to using the standard Rails enums, which means that we are unable to continue supporting enumerize in this gem.

2023-03-17 20:10 UTC, monkeyci commented on lib/activeadmin_addons/addons/tag_builder.rb
> +      raise "you need to pass an enum attribute" unless @enum_attr
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Add empty line after guard clause.

2023-03-17 20:10 UTC, monkeyci commented on spec/dummy/app/models/invoice.rb
> +    approved: 'approved',
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Avoid comma after the last item of a hash.

2023-03-17 20:45 UTC, difernandez requested changes
Couple small things, looks good!

2023-03-17 20:45 UTC, difernandez commented on lib/activeadmin_addons/addons/tag_builder.rb
> +      raise "you need to pass an enum attribute" unless @enum_attr
with the change in `display_data`, `@enum_attr` is no longer used. We could chage this to just:
```ruby
raise "you need to pass an enum attribute" unless rails_enum_attr?
```

2023-03-17 20:45 UTC, difernandez commented on lib/activeadmin_addons/support/enumerize_formtastic_support.rb
this whole file was for enumerize support, we should just delete it

2023-03-17 21:02 UTC, difernandez approved these changes

2023-03-20 12:45 UTC, ldlsegovia approved these changes

2023-03-20 12:49 UTC, merged